# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtshr < Formula
  desc "Secure, zero-knowledge text sharing CLI"
  homepage "https://github.com/aren55555/txtshr"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.1/txtshr_darwin_amd64.tar.gz"
      sha256 "c602eed3e69a01b65027105a84f512614746b70512ec3a72b61c12fcea43030e"

      define_method(:install) do
        bin.install "txtshr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.1/txtshr_darwin_arm64.tar.gz"
      sha256 "88dc9ccbf65ae282038b01b0b4fcdd3e1d004f98960f315db8bb75c469c21ab5"

      define_method(:install) do
        bin.install "txtshr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.1/txtshr_linux_amd64.tar.gz"
      sha256 "ee4ad0c03103682cd7e65b367611950f5e3b0cf4563537993db8eba946b38f3a"
      define_method(:install) do
        bin.install "txtshr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.1/txtshr_linux_arm64.tar.gz"
      sha256 "b34cf8efd72f3bb2a381aa7bdec64865c35b2d2e50fdef20c4212dbd8f927331"
      define_method(:install) do
        bin.install "txtshr"
      end
    end
  end

  test do
    system "#{bin}/txtshr", "--help"
  end
end
