# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtshr < Formula
  desc "Secure, zero-knowledge text sharing CLI"
  homepage "https://github.com/aren55555/txtshr"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.4/txtshr_darwin_amd64.tar.gz"
      sha256 "8490e2b8da6825de0ffbb48c4414b4e69411af3573c4ae5afe64c74cbb92be43"

      define_method(:install) do
        bin.install "txtshr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.4/txtshr_darwin_arm64.tar.gz"
      sha256 "b3f825976692f9c9872eafb4ba5f4ec64a28d1cc7166d816e9632a43c36e6cb1"

      define_method(:install) do
        bin.install "txtshr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.4/txtshr_linux_amd64.tar.gz"
      sha256 "8547d0f272580403e9e95e9e758154fa8a7fb18e6608c323a7eb2a001c2bd7a7"
      define_method(:install) do
        bin.install "txtshr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aren55555/txtshr/releases/download/v0.1.4/txtshr_linux_arm64.tar.gz"
      sha256 "4d5dc53760ec2e9f4131c4158f232486f759ceaaaa9f31fabc7d4cfd19525ed6"
      define_method(:install) do
        bin.install "txtshr"
      end
    end
  end

  test do
    system "#{bin}/txtshr", "--help"
  end
end
